[package]
name = "tla"
version = "0.1.0"
description = "A CLI tool for compressing and encrypting a directory. (tar, lzma, aes & des)"
repository = "https://github.com/hzqd/tla"
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "~3.0"
features = ["derive"]

[dependencies]
tar = "0.4"
xz2 = "0.1"
ades = "0.1"
aoko = "0.2"